@HOST = http://localhost:8080
@HOSTR= https://winmarchant.azurewebsites.net
@AUTH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWMyMGQyMzUwNGM4NGRjZTcxOTc5NTIiLCJlbWFpbCI6IiIsImxhc3RuYW1lIjoiIiwiY29udGFjdE51bWJlciI6ImZvdW5kZXJAbXlwYWFhLmNvbSIsIndlYkFjY2VzcyI6MSwicHJvZHVjdElkIjpbXSwicmVmcmVzaEtleSI6IlVnSmRNNm51dG5mVVA5Vk5uY1pHUEE9PSIsImlhdCI6MTcxMzE1NjIxNH0.zAQZJilI8Zx8QvUGf6c4c-P1Gt8a1rBeJbmtlz8j40U
@TESTID = 65a7df3e98a69017fb609125
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/distributor HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"blogTitle":"esse",
"category":"adipisicing",
"currency":"consectetur",
"telephone":"601780485308",
"email":"cons2sq1u4dat@ucode.ai",
"state":"ullamco",
"active":"false",
"productid":"657e7eb75e1f0a24b70262bc",
"contactNumber":"6301432716937171",
"name":"ipsum",
"address":"Culpa elit duis laborum cupidatat.",
"city":"proident",
"zipcode":"idclf"

}

###

GET {{HOST}}/distributor? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/distributor?blogTitle=esse&category=adipisicin&currency=consectetu&telephone=6017804853&email=consequat@&state=ullamco&active=false&productid=estclf&contactNumber=6017169371&name=ipsum&address=Culpa elit&city=proident&zipcode=idclf&country=dolor&productname=commodo&serviceType=1.35 HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOSTR}}/distributor/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/distributor/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"blogTitle":"esse",
"category":"adipisicing",
"currency":"consectetur",
"telephone":"601780485308",
"email":"consequat@ucode.ai",
"state":"ullamco",
"active":"false",
"productid":"estclf",
"contactNumber":"601716937174",
"name":"ipsum",
"address":"Culpa elit duis laborum cupidatat.",
"city":"proident",
"zipcode":"idclf",
"country":"dolor",
"productname":"commodo",
"serviceType":"1.35"
}
###
PATCH {{HOST}}/distributor/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"blogTitle":"esse",
"category":"adipisicing",
"currency":"consectetur",
"telephone":"601780485308",
"email":"consequat@ucode.ai",
"state":"ullamco",
"active":"false",
"productid":"estclf",
"contactNumber":"601716937174",
"name":"ipsum",
"address":"Culpa elit duis laborum cupidatat.",
"city":"proident",
"zipcode":"idclf",
"country":"dolor",
"productname":"commodo",
"serviceType":"1.35"
}
###
DELETE {{HOST}}/distributor/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
