@HOST = https://winmarchant.azurewebsites.net
@HOSTL = http://localhost:8082
@AUTH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMTFlYjRmMC1kYzdlLTQzNTUtODQxMS0wNDZhNGEzNWI0YjAiLCJlbWFpbCI6ImthemFkNzlAZ21haWwuY29tIiwidWlkIjoiMTQxOTk3IiwibmFtZSI6Ik1EIEFidWwgS2FsYW0gQXphZCIsInVzZXJuYW1lIjoia2FsYW0iLCJjb3VudHJ5IjoiMTMwIiwibW9iaWxlbm8iOiI2MDE3NjcwMTk0NiIsInVzZXJUeXBlIjoyLCJyZWZyZXNoS2V5IjoiQW5vbWh2eG5RMGN2VVZVOER0L0IxQT09IiwiaWF0IjoxNzI5MzM0MDUzLCJleHAiOjE3MzE5MjYwNTN9.P8MgrJoSDe1hxA1ARxFobeW_3cXNr4_OiSHgTb5yl68
@AUTH_F=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmYwZWUyOWYyMDIxZDdiNmI0MmMyNTIiLCJjb250YWN0TnVtYmVyVHlwZSI6MiwibmFtZSI6IkFmbmFuIEFobWVkIiwidXNlclR5cGUiOjQsImVtYWlsIjoiZXhjb2RlLm5ldEBnbWFpbC5jb20iLCJtb2JpbGUiOiIiLCJ2ZXJpZmllZCI6MSwiY291bnRyeSI6Im15IiwidXNlcm5hbWUiOiJhZm5hbiIsImludHJvZHVjZXIiOiJrYWxhbSIsImlhdCI6MTcyNzUwODE3OCwiZXhwIjoxNzMwMTAwMTc4fQ.S6b7rOl-5RHgrfcKZH_fwzkXdSrwgXnin3jtPCdlrPs
//{"name":"Afnan Ahmed","mobileno":"","username":"afnan","email":"excode.net@gmail.com","userType":4,"userId":"66f0ee29f2021d7b6b42c252","introducer":"kalam","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmYwZWUyOWYyMDIxZDdiNmI0MmMyNTIiLCJjb250YWN0TnVtYmVyVHlwZSI6MiwibmFtZSI6IkFmbmFuIEFobWVkIiwidXNlclR5cGUiOjQsImVtYWlsIjoiZXhjb2RlLm5ldEBnbWFpbC5jb20iLCJtb2JpbGUiOiIiLCJ2ZXJpZmllZCI6MSwiY291bnRyeSI6Im15IiwidXNlcm5hbWUiOiJhZm5hbiIsImludHJvZHVjZXIiOiJrYWxhbSIsImlhdCI6MTcyNzUwODE3OCwiZXhwIjoxNzMwMTAwMTc4fQ.S6b7rOl-5RHgrfcKZH_fwzkXdSrwgXnin3jtPCdlrPs","refresh":"6e6yfJ0hebeG2c9ifO2i0J2I1Udz7Ib16Nbi4I2scI2n5R25cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmYwZWUyOWYyMDIxZDdiNmI0MmMyNTIiLCJjb250YWN0TnVtYmVyVHlwZSI6MiwibmFtZSI6IkFmbmFuIEFobWVkIiwidXNlclR5cGUiOjQsImVtYWlsIjoiZXhjb2RlLm5ldEBnbWFpbC5jb20iLCJtb2JpbGUiOiIiLCJ2ZXJpZmllZCI6MSwiY291bnRyeSI6Im15IiwidXNlcm5hbWUiOiJhZm5hbiIsImludHJvZHVjZXIiOiJrYWxhbSIsImlhdCI6MTcyNzUwODE3OH0.qiekT_wL7gaaWqhGK2YU4ei-AQ4vKNW84fy-r03zS8c.02"}
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/hierarchy HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"distributor":"false",
"contactNumber":"601714316041",
"productid":"estclf",
"introducer":"601778100897"
}

###

GET {{HOST}}/hierarchy?productid=60828a990b94d12774a900cf&productid_mode=equals HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/hierarchy?distributor=false&contactNumber=6017143160&productid=estclf&introducer=6017781008 HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/hierarchy/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/hierarchy/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"distributor":"false",
"contactNumber":"601714316041",
"productid":"estclf",
"introducer":"601778100897"
}
###
PATCH {{HOST}}/hierarchy/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"distributor":"false",
"contactNumber":"601714316041",
"productid":"estclf",
"introducer":"601778100897"
}
###
DELETE {{HOST}}/hierarchy/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 



### createBy,createAt,username, productid, parentUsername
GET {{HOST}}/hierarchy/ref?productId=66e665de966efc2edaa97cf0&xI=ahmad HTTP/1.1
Authorization: Bearer {{AUTH_F}}
content-type: application/json
project-code:66efa1fcfb844876e472f02b

### createBy,createAt,username, productid, parentUsername
GET {{HOST}}/hierarchy/all/level/?productId=66e665de966efc2edaa97cf0&xI=ahmad HTTP/1.1
Authorization: Bearer {{AUTH_F}}
content-type: application/json
project_code:66efa1fcfb844876e472f02b


### createBy,createAt,username, productid, parentUsername
GET {{HOST}}/hierarchy/all/org_chart2/u?productId=66e665de966efc2edaa97cf0&xI=denkayo HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json
project_code:66efa1fcfb844876e472f02b
###
http://localhost:8082/hierarchy/all/org_chart2/u?productId=66e665de966efc2edaa97cf0
Authorization: Bearer {{AUTH}}
content-type: application/json
project_code:66efa1fcfb844876e472f02b
### createBy,createAt,username, productid, parentUsername
GET {{HOST}}/hierarchy/all/level3/?productId=66e665de966efc2edaa97cf0&xI=angie3 HTTP/1.1
Authorization: Bearer {{AUTH_F}}
content-type: application/json
project_code:66efa1fcfb844876e472f02b



###

POST {{HOSTL}}/hierarchy/addNew/reg HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
    "contactNumber":"test456",
    "introducer":"kalam",
    "productid":"66e665de966efc2edaa97cf0",
    "category":"FC",
    "price":"90"
}

###

POST {{HOST}}/hierarchy/check/reg HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
    "contactNumber":"ffff",
    "introducer":"ahmad",
    "productid":"66e665de966efc2edaa97cf0",
    "category":"FP260"
}
###

POST {{HOST}}/hierarchy/addNew/reward HTTP/1.1

content-type: application/json

{
    "contactNumber":"kalam",
    "introducer":"ahmad",
    "productid":"66e665de966efc2edaa97cf0",
    "upline":"lean",
    "position":"L"
}


###

POST {{HOST}}/hierarchy/check/reg HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
    "contactNumber":"ffff",
    "introducer":"ahmad",
    "productid":"66e665de966efc2edaa97cf0",
    "category":"FP260"
}

###

POST {{HOST}}/hierarchy/sync HTTP/1.1
Authorization: Bearer {{AUTH}}
project_code:66efa1fcfb844876e472f02b
content-type: application/json

{
    
    "productid":"66e665de966efc2edaa97cf0"
 
}
###

GET {{HOST}}/hierarchy/all/org_chart2/count?xI=michellefong HTTP/1.1

content-type: application/json

{
    "contactNumber":"michellefong",
    "introducer":"ahmad",
    "productid":"66e665de966efc2edaa97cf0",
    "upline":"lean",
    "position":"L"
}


###

POST {{HOST}}/hierarchy/addNew/reward/check HTTP/1.1
content-type: application/json

{
    "contactNumber":"alwinsuccess",
    "introducer":"safinatee",
    "productid":"66e665de966efc2edaa97cf0"
}


###
GET {{HOST}}/hierarchy/all/org_chart2/u?productId=66e665de966efc2edaa97cf0&xI=denkayo
Authorization: Bearer {{AUTH}}
project_code:66efa1fcfb844876e472f02b



###

POST {{HOST}}/hierarchy/placement/reg/u2 HTTP/1.1
content-type: application/json

{
    "contactNumber":"saaban69",
    "introducer":"ajiree",
    "productid":"66e665de966efc2edaa97cf0",
    "upline":"apani51",
    "position":"L"
}

###

POST {{HOST}}/hierarchy/placement/reg HTTP/1.1
content-type: application/json

{
    "contactNumber":"odabilloinare769",
    "introducer":"selawat69",
    "productid":"66e665de966efc2edaa97cf0",
    "upline":"anom69",
    "position":"L"
}
###

POST {{HOST}}/hierarchy/placement/reg HTTP/1.1
content-type: application/json

{
    "contactNumber":"chesmyo",
    "introducer":"flo10",
    "productid":"66e665de966efc2edaa97cf0",
    "upline":"cashflow",
    "position":"L"
}

###
#const storeCreatedBy =req.body.storeCreatedBy;
   #const merchat_username =req.body.merchat_username;
   # const customer =req.body.customer;
   #const productId =req.body.productId;
    #const amount =req.body.amount;
    
POST {{HOSTL}}/hierarchy/reward/purchase HTTP/1.1
content-type: application/json

{
    "storeCreatedBy":"tuahnusantara@gmail.com",
    "merchat_username":"aura7",
    "productId":"66e665de966efc2edaa97cf0",
    "customer":"ahmad",
    "trx_id":"675c464d4c34bb2449594aa8",
    "storeName":"Selmah Fashion"
}
###
@TRX=675c464d4c34bb2449594aa8
@URL=https://alifpay-merchant-uat-edc6aucnchbracbz.southeastasia-01.azurewebsites.net
@TRX2=675ad60abc15139301867125
@URL2=https://merchant.alifpay.com.my
###
GET {{URL2}}/transactions/taskcompleted/{{TRX}} HTTP/1.1
###

GET {{URL}}/transactions/taskcheck/{{TRX2}} HTTP/1.1

###
@DD =https://winmarchant.azurewebsites.net
###

POST {{HOST}}/hierarchy/reward/payhub  HTTP/1.1
content-type: application/json

{

    "alifPayUsername":"fajrain68",
    "productId":"66e665de966efc2edaa97cf0",
    "trx_id":"68556f68f759d7045cca1b2d",
    "productName":"ETNB"
}

###

POST {{HOSTL}}/hierarchy/addNewBU/reg  HTTP/1.1
content-type: application/json

{
    "contactNumber": "excodetemp111",
    "introducer": "afnan",
    "productid":"66e665de966efc2edaa97cf0",
    "category": "BU"
}

###

GET {{HOSTL}}/hierarchy/single/level/ahmad?productId=66e665de966efc2edaa97cf0  HTTP/1.1