@REMOTE_HOST = https://plankton-app-anvjc.ondigitalocean.app
@LOCAL_HOST = http://localhost:8082
@AUTH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2M2OGYyNzA3NzIzODA0NTQwOGZhYzkiLCJjb250YWN0TnVtYmVyVHlwZSI6MSwibmFtZSI6IkthbGFtIEF6YWQiLCJ1c2VyVHlwZSI6NCwiZW1haWwiOiJrYXphZDc5QGdtYWlsLmNvbSIsIm1vYmlsZSI6IiIsInZlcmlmaWVkIjoxLCJjb3VudHJ5IjoiIiwibGFuZ3VhZ2UiOiJlbiIsIm5vdGlmaWNhdGlvbiI6dHJ1ZSwidXNlcm5hbWUiOiJrYXphZDc5QGdtYWlsLmNvbSIsInByb3ZpZGVyIjoid2luYW5kd2luZ3MiLCJvd25lciI6W10sImlhdCI6MTc1MjU1MTE1NywiZXhwIjoxNzUzMTU1OTU3fQ.0RNy2EKXzGVO0_cQ3WB7ssZtHzColOT-gmBM3a8ELAU

### SELL:: Latest 5 sell
GET {{LOCAL_HOST}}/sell/latest-sell HTTP/1.1
Authorization: Bearer {{AUTH}}

### REDEEM: Latest 5 redeem
GET {{LOCAL_HOST}}/redeem/latest-redeem HTTP/1.1
Authorization: Bearer {{AUTH}}

### Analytics
GET {{LOCAL_HOST}}/analytics HTTP/1.1
Authorization: Bearer {{AUTH}}
