@HOST = http://localhost:8080
@AUTH = authtoken
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/productblog HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"active":"false",
"title":"nonclf",
"details":"Ea commodo sint veniam ex eu eu.",
"productid":"adipisicing",
"categoryid":"eaclf",
"photo":""
}

###

GET {{HOST}}/productblog? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/productblog?active=false&title=nonclf&details=Ea commodo&productid=adipisicin&categoryid=eaclf&photo= HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/productblog/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/productblog/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"active":"false",
"title":"nonclf",
"details":"Ea commodo sint veniam ex eu eu.",
"productid":"adipisicing",
"categoryid":"eaclf",
"photo":""
}
###
PATCH {{HOST}}/productblog/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"active":"false",
"title":"nonclf",
"details":"Ea commodo sint veniam ex eu eu.",
"productid":"adipisicing",
"categoryid":"eaclf",
"photo":""
}
###
DELETE {{HOST}}/productblog/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
