@HOST = http://localhost:8082
@AUTH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmU2NTM5ZTY4NWFhZTViOGYxZjMyNmUiLCJlbWFpbCI6ImV4Y29kZS5uZXRAZ21haWwuY29tIiwiZmlyc3RuYW1lIjoiQWxpZlBheSIsImxhc3RuYW1lIjoiR3JvdXAiLCJjb250YWN0TnVtYmVyIjoiNjAxNzY3MDE5NDUiLCJ3ZWJBY2Nlc3MiOjEsInByb2R1Y3RJZCI6WyI2NmU3OGQ2ZTU0Y2VkNzEyM2ExODQ3OTYiLCI2NmU2NjVkZTk2NmVmYzJlZGFhOTdjZjAiLCI2NmU2NWYxZTJmM2VmODFiNDc1NDRjNzYiXSwicmVmcmVzaEtleSI6InZpMFNOdi8zekRQQVlxTGtYSnR0NUE9PSIsImlhdCI6MTcyODQ0NTYwNn0.DhxjP0wuuC9D_TiqDgB4jtODs-RYyiSOK5dw7ju3zd4
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/sell HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"quantity":"1.35",
"unitprice":"1.35",
"total":"1.35",
"productid":"utclf",
"sellerNumber":"601790661886",
"contactNumber":"601739649935"
}

###

GET {{HOST}}/sell? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/sell?quantity=1.35&unitprice=1.35&total=1.35&productid=utclf&sellerNumber=6017906618&contactNumber=6017396499 HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/sell/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/sell/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"quantity":"1.35",
"unitprice":"1.35",
"total":"1.35",
"productid":"utclf",
"sellerNumber":"601790661886",
"contactNumber":"601739649935"
}
###
PATCH {{HOST}}/sell/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"quantity":"1.35",
"unitprice":"1.35",
"total":"1.35",
"productid":"utclf",
"sellerNumber":"601790661886",
"contactNumber":"601739649935"
}
###
DELETE {{HOST}}/sell/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
