@HOST = http://localhost:8080
@HOST2 = http://localhost:8081
@AUTH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVhYjUzZjZlMTMzMzBhZTQzYTBlMDYiLCJlbWFpbCI6InRlc3RAdWNvZGUuYWkiLCJmaXJzdG5hbWUiOiJ1Q29kZSIsImxhc3RuYW1lIjoiVGVzdCIsImNvbnRhY3ROdW1iZXIiOiI2MDE3NjQwODI1MCIsIndlYkFjY2VzcyI6MSwicHJvZHVjdElkIjpbIjY1N2U4MDg2NTZjMzA2MjcxN2FmY2Q3MCIsIjY1N2U3ZWI3NWUxZjBhMjRiNzAyNjJiYyIsIjY1N2U3OTY2NWUxZjQ2MjAyYjMyMjliOSJdLCJyZWZyZXNoS2V5IjoiUkEzc1IwQkFIYS9PMWZsMFF4eEVxdz09IiwiaWF0IjoxNzA1NDY4OTMwfQ.AY9wFfrho3D1nO4--HpZOQqHYNciZos7yJI8RadaLeE
@AUTH2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDdkNGRiNjk2ZmYxNTAwMTNjMWNkMjEiLCJjb250YWN0TnVtYmVyIjoiODgwMTU1MjM3NzIwNSIsImNvdW50cnkiOiJiZCIsIm5hbWUiOiJLYWxhbSBBemFkIiwicmVmcmVzaEtleSI6InVRakZwOXRWdU9wZHNNNE0wZDRxU1E9PSIsImlhdCI6MTcwNTQ3MjcxNCwiZXhwIjoxNzA3NDcyNzE0fQ.DDohc4pSJTCOasjPHvVoGLmyfZ0JRiXjasqfQL89aSo
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/transaction HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"amount":"1.35",
"quantity":"1.35",
"rtype":"1",
"productid":"exclf",
"contactNumber":"601728794239",
"particular":"officia"
}

###

GET {{HOST}}/transaction HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/transaction?amount=1.35&quantity=1.35&rtype=1&productid=exclf&contactNumber=6017287942&particular=officia HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/transaction/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/transaction/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"amount":"1.35",
"quantity":"1.35",
"rtype":"1",
"productid":"exclf",
"contactNumber":"601728794239",
"particular":"officia"
}
###
PATCH {{HOST}}/transaction/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"amount":"1.35",
"quantity":"1.35",
"rtype":"1",
"productid":"exclf",
"contactNumber":"601728794239",
"particular":"officia"
}
###
DELETE {{HOST}}/transaction/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 



###

GET {{HOST2}}/transaction?productid=657e808656c3062717afcd70 HTTP/1.1
Authorization: Bearer {{AUTH2}}