@HOST = https://winmarchant.azurewebsites.net
@HOST = http://localhost:8080
@AUTH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWMyMGQyMzUwNGM4NGRjZTcxOTc5NTIiLCJlbWFpbCI6ImZvdW5kZXJAbXlwYWFhLmNvbSIsImxhc3RuYW1lIjoiIiwiY29udGFjdE51bWJlciI6ImZvdW5kZXJAbXlwYWFhLmNvbSIsIndlYkFjY2VzcyI6MSwicHJvZHVjdElkIjpbXSwicmVmcmVzaEtleSI6IkY2REZCZHE4WmpxK3phZE1BeHN2UlE9PSIsImlhdCI6MTcxMzM0MzcxOH0.f8Y9xsgTYOXENtPDQJP8xFN8hsO6uyY794RVkdboIc8
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"founder@mypaaa.com",
"password":"123456"
}
###
POST {{HOST}}/users HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"lastname":"quiclf",
"usertype":"1",
"firstname":"velit",
"password":"ucode1234",
"contactNumber":"601775735722",
"email":"commodo@ucode.ai8"
}

###

#MAIN REGISTRATION for NODEJS VERSION
POST {{HOST}}/users/reg HTTP/1.1
content-type: application/json
    
{
"email":"test@ucode.ai",
"password":"123456",
"firstname":"uCode",
"lastname":"Test",
"usertype":"0",
"contactNumber":"601764082501"
}
###
#MAIN REGISTRATION for Java Spring boot
POST {{HOST}}/reg HTTP/1.1
content-type: application/json
 
{
"country":"my",
"password":"123456",
"name":"Kalma",
"lastname":"Test",
"usertype":"0",
"contactNumber":"60176408250"
}
###

GET {{HOST}}/users? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/users?lastname=quiclf&usertype=1&firstname=velit&contactNumber=6017757357&email=commodo@uc HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/users/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/users/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"lastname":"quiclf",
"usertype":"1",
"firstname":"velit",
"password":"ucode1234",
"contactNumber":"601775735722",
"email":"commodo@ucode.ai8"
}
###
PATCH {{HOST}}/users/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"lastname":"quiclf",
"usertype":"1",
"firstname":"velit",
"password":"ucode1234",
"contactNumber":"601775735722",
"email":"commodo@ucode.ai8"
}
###
DELETE {{HOST}}/users/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 


###
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"contactNumber":"8801552377205",
"password":"123456"
}



###
POST {{HOST}}/reg HTTP/1.1
content-type: application/json

{
"contactNumber":"60176701946",
"password":"123456"
}


////dash

###
GET {{HOST}}/redeem/dash  HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/promotion/dash  HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/reward/dash HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/sell/dash  HTTP/1.1
Authorization: Bearer {{AUTH}}

###       
GET {{HOST}}/users/dash HTTP/1.1
Authorization: Bearer {{AUTH}}