@HOST = https://winmarchant.azurewebsites.net
@HOST = http://localhost:8080
@AUTH = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWMyMGQyMzUwNGM4NGRjZTcxOTc5NTIiLCJlbWFpbCI6ImZvdW5kZXJAbXlwYWFhLmNvbSIsImxhc3RuYW1lIjoiIiwiY29udGFjdE51bWJlciI6ImZvdW5kZXJAbXlwYWFhLmNvbSIsIndlYkFjY2VzcyI6MSwicHJvZHVjdElkIjpbXSwicmVmcmVzaEtleSI6IkY2REZCZHE4WmpxK3phZE1BeHN2UlE9PSIsImlhdCI6MTcxMzM0MzcxOH0.f8Y9xsgTYOXENtPDQJP8xFN8hsO6uyY794RVkdboIc8
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"wegagit687@idsho.com",
"password":"123456"
}

### 
POST {{HOST}}/users HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"lastname":"quiclf",
"usertype":"1",
"firstname":"velit",
"contactNumber":"601775735723",
"email":"commodo1@ucode.ai8"
}

### 
POST {{HOST}}/users/reg HTTP/1.1
content-type: application/json
    
{
"email":"excode.net@gmail.com",
"firstname":"Kalam Azad",
"lastname":"Azad",
"usertype":"1",
"contactNumber":"601764082504"
}

###   
POST {{HOST}}/users/emailOtp HTTP/1.1
content-type: application/json

{
    "email":"excode.net@gmail.com"
}
###
PATCH {{HOST}}/users/verifyEmailOtp HTTP/1.1
content-type: application/json

{
    "email":"wegagit687@idsho.com",
    "otp":"261313"
}

###
POST {{HOST}}/users/resetPasswordInit HTTP/1.1
content-type: application/json

{
    "email":"excode.net@gmail.com"
}

###
PATCH {{HOST}}/users/resetPasswordFinish HTTP/1.1
content-type: application/json

{
    "email":"excode.net@gmail.com",
    "otp":"419977",
    "newPassword":"123456"
}

### 
PATCH {{HOST}}/users/changePassword HTTP/1.1
content-type: application/json
Authorization: Bearer {{AUTH}}

{
    "oldPassword":"1234567",
    "newPassword":"123456"
}


###
GET {{HOST}}/users? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/users?lastname=quiclf&usertype=1&firstname=velit&contactNumber=6017757357&email=commodo@uc HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/users/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/users/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"lastname":"quiclf",
"usertype":"1",
"firstname":"velit",
"password":"ucode1234",
"contactNumber":"601775735722",
"email":"commodo@ucode.ai8"
}
###
PATCH {{HOST}}/users/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"lastname":"quiclf",
"usertype":"1",
"firstname":"velit",
"password":"ucode1234",
"contactNumber":"601775735722",
"email":"commodo@ucode.ai8"
}
###
DELETE {{HOST}}/users/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 


###
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"contactNumber":"8801552377205",
"password":"123456"
}



###
POST {{HOST}}/reg HTTP/1.1
content-type: application/json

{
"contactNumber":"60176701946",
"password":"123456"
}



////dash

###
GET {{HOST}}/redeem/dash  HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/promotion/dash  HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/reward/dash HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/sell/dash  HTTP/1.1
Authorization: Bearer {{AUTH}}

###       
GET {{HOST}}/users/dash HTTP/1.1
Authorization: Bearer {{AUTH}}